In [1]:
# run python script from path: src\data\get_ferien.py

%run ../src/data/get_ferien.py

Fehler beim Abrufen der Daten für Nordrhein-Westfalen Winterferien: No tables found
Fehler beim Abrufen der Daten für Hessen Winterferien: No tables found

In [1]:
import pandas as pd
import numpy as np
import requests

In [3]:



def ersetze_umlaute(bundesland):
    umlaute = {"ä": "ae", "ö": "oe", "ü": "ue", "ß": "ss"}
    for original, ersatz in umlaute.items():
        bundesland = bundesland.replace(original, ersatz)
    return bundesland


bundesländer = [
    "Brandenburg",
    "Baden-Wuerttemberg",
    "Mecklenburg-Vorpommern",
    "Bayern",
    "Niedersachsen",
    "Nordrhein-Westfalen",
    "Rheinland-Pfalz",
    "Berlin",
    "Hamburg",
    "Hessen",
]
# ferienarten = ["ostern", "pfingsten", "sommer", "herbst", "weihnachten", "winter"]
ferienarten = ["winter"]

# Liste für die gesammelten DataFrames
df_liste = []

for ferienart in ferienarten:
    for land in bundesländer:
        url_land = ersetze_umlaute(land).lower()
        url = f"https://www.schulferien.org/deutschland/ferien/{ferienart}/{url_land}/"
        try:
            response = requests.get(url)
            tables = pd.read_html(response.content)
            # Nehmen Sie an, dass die erste Tabelle die gewünschten Daten enthält
            df = tables[0]
            df["Bundesland"] = land  # Fügen Sie eine Spalte für das Bundesland hinzu
            df["Ferienart"] = (
                ferienart.capitalize()
            )  # Fügen Sie eine Spalte für die Ferienart hinzu
            df_liste.append(df)
        except Exception as e:
            print(
                f"Fehler beim Abrufen der Daten für {land} {ferienart.capitalize()}ferien: {e}"
            )

gesamt_df = pd.concat(df_liste, ignore_index=True)

Fehler beim Abrufen der Daten für Nordrhein-Westfalen Winterferien: html5lib not found, please install it
Fehler beim Abrufen der Daten für Hessen Winterferien: html5lib not found, please install it

In [15]:
df_liste = []
url = f"https://www.schulferien.org/deutschland/ferien/winter/brandenburg/"

response = requests.get(url)
tables = pd.read_html(response.content)
# Nehmen Sie an, dass die erste Tabelle die gewünschten Daten enthält
for table in tables:
    df = table
    df["Bundesland"] = "brandenburg"  # Fügen Sie eine Spalte für das Bundesland hinzu
    df["Ferienart"] = "winter"
    df_liste.append(df)
gesamt_df = pd.concat(df_liste, ignore_index=True)

In [2]:
gesamt_df

                 Bundesland Ferienart Startdatum   Enddatum
0               Brandenburg    Winter 1991-02-25 1991-03-08
1               Brandenburg    Winter 1992-02-08 1992-02-22
2               Brandenburg    Winter 1993-02-11 1993-02-24
3               Brandenburg    Winter 1994-01-31 1994-02-12
4               Brandenburg    Winter 1995-01-30 1995-02-11
..                      ...       ...        ...        ...
236  Mecklenburg-Vorpommern    Winter 2021-02-19        NaT
237  Mecklenburg-Vorpommern    Winter 2022-02-05 2022-02-17
238  Mecklenburg-Vorpommern    Winter 2022-02-18        NaT
239  Mecklenburg-Vorpommern    Winter 2028-02-05 2028-02-17
240  Mecklenburg-Vorpommern    Winter 2028-02-18        NaT

[214 rows x 4 columns]